################################################
# Template for Tables - SearchStore
################################################

AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

################################################
# Parameters
################################################
Parameters:
  Application:
    Type: String
  Module:
    Type: String
  Environment:
    Type: String
    Default: dev
    Description: Environment name
  LogLevel:
    Type: String
    Default: INFO
  RetentionInDays:
    Type: Number
    Default: 30
    Description: CloudWatch Logs retention period for Lambda functions
  NodeLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Node Layer NodeDependenciesLayer ARN

Globals:
  Function:
    Runtime: nodejs14.x
    Handler: index.handler
    Layers:
      - !Ref NodeLayerArn
    Timeout: 5
    Tracing: Active
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        LOG_LEVEL: !Ref LogLevel

################################################
# Resources
################################################
Resources:
  # SearchStoreTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: !Sub ${Application}-${Environment}-SearchStore
  #     Tags:
  #       - Key: "Environment"
  #         Value: !Ref Environment
  #       - Key: "Application"
  #         Value: !Ref Application
  #     AttributeDefinitions:
  #       - AttributeName: id
  #         AttributeType: S
  #       - AttributeName: userId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH
  #     GlobalSecondaryIndexes:
  #       - IndexName: byCustomerUserId
  #         KeySchema:
  #           - AttributeName: userId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #     StreamSpecification:
  #       StreamViewType: NEW_AND_OLD_IMAGES
  #     BillingMode: PAY_PER_REQUEST
  #     SSESpecification:
  #       SSEEnabled: true
  #     PointInTimeRecoverySpecification:
  #       PointInTimeRecoveryEnabled: true
  #   DeletionPolicy: Retain

  ################################################
  # Functions
  ################################################
  SearchStore:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Application}-${Environment}-SearchStore-Function
      Handler: manage_searchStore.handler
      CodeUri: ./src
      MemorySize: 768
      Tags:
        Application: !Ref Application
        Environment: !Ref Environment
        Module: !Ref Module
      Environment:
        Variables:
          Application: !Ref Application
          INDEX_NAME: !Sub ${Application}-${Environment}-store
          LOG_LEVEL: !Ref LogLevel
      Policies:
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - es:*
              Resource:
                - !Sub "arn:${AWS::Partition}:es:${AWS::Region}:${AWS::AccountId}:domain/${Application}-${Environment}-es"
                - !Sub "arn:${AWS::Partition}:geo:${AWS::Region}:${AWS::AccountId}:route-calculator/${Application}-${Environment}-platform-Esri-routeCalculator"

  SearchStoreLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SearchStore}"
      RetentionInDays: !Ref RetentionInDays
